# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#permalink:        pretty
permalink: 		   /:title

# Setup
title:            Airing Pods
tagline:          'Conversations on Podcasts and in general listening content'
description:      'Listen on 50 topics'
url:              http://blog.airingpods.com
baseurl:          /

author:
  name:           'Airing Pods'
  url:            https://twitter.com/airingpods

paginate:         5

# Custom vars
airingpodsurl:    http://www.airingpods.com

#for sitemap plugin
exclude:
    - "/404.html"