# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
#permalink:        pretty
permalink: 		   :title/

# Setup
title:            Airing Pods
tagline:          'Conversations on Audio Podcasts and in general listening content'
shorttagline:     'Conversations on Audio Podcasts'
description:      'Audio Podcasts'
url:              http://blog.airingpods.com
baseurl:          

author:
  name:           'Airing Pods'
  url:            https://twitter.com/airingpods

paginate:         5

# Custom vars
airingpodsurl:    http://www.airingpods.com

gems:
  - jekyll-sitemap